import Foundation
import Combine

// The Go binding generated by `gomobile bind -prefix DNSpire ./mobile` exposes
// ObjC/Swift symbols as DNSpireMobile..., because the package name is `mobile`.
// The framework module itself is DNSpireCore.
import DNSpireCore

enum TunnelStatus: String {
    case stopped
    case starting
    case mtuTesting = "mtu_testing"
    case sessionInit = "session_init"
    case connected
    case reconnecting
    case error
}

/// Bridges the Go-side Tunnel object into SwiftUI. Owns the underlying
/// DNSpireMobileTunnel handle and keeps @Published state for the UI to observe.
@MainActor
final class TunnelController: ObservableObject {
    @Published private(set) var status: TunnelStatus = .stopped
    @Published private(set) var statusDetail: String = ""
    @Published private(set) var socksAddress: String = ""
    @Published private(set) var lastError: String?

    private var tunnel: DNSpireMobileTunnel?
    private weak var logStore: LogStore?

    /// Hooks the controller up to a LogStore so Go-side log lines surface in
    /// the UI's Logs tab. Called once from DNSpireApp.task.
    func attach(logStore: LogStore) {
        self.logStore = logStore
    }

    func start(configJSON: String, resolversText: String) {
        guard tunnel == nil else { return }

        let scratchDir = scratchDirectoryURL().path
        let t = DNSpireMobileNewTunnel()!

        let logSink = LogSink { [weak self] line in
            Task { @MainActor in
                self?.logStore?.append(line)
            }
        }
        let statusSink = StatusSink { [weak self] state in
            Task { @MainActor in
                self?.applyStatusString(state)
            }
        }
        t.setLogCallback(logSink)
        t.setStatusCallback(statusSink)
        self.tunnel = t

        do {
            try t.start(configJSON, resolversText: resolversText, scratchDir: scratchDir)
            self.socksAddress = t.socksAddress()
            self.lastError = nil
        } catch {
            self.tunnel = nil
            self.status = .error
            self.lastError = error.localizedDescription
            self.logStore?.append("[ui] start failed: \(error.localizedDescription)")
        }
    }

    func stop() {
        guard let t = tunnel else { return }
        do {
            try t.stop()
        } catch {
            self.logStore?.append("[ui] stop returned: \(error.localizedDescription)")
        }
        self.tunnel = nil
        self.socksAddress = ""
    }

    private func applyStatusString(_ state: String) {
        if state.hasPrefix("error:") {
            self.status = .error
            self.lastError = String(state.dropFirst("error:".count))
            self.statusDetail = state
            return
        }
        self.statusDetail = state
        self.status = TunnelStatus(rawValue: state) ?? .starting
    }

    private func scratchDirectoryURL() -> URL {
        let base = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
        let dir = base.appendingPathComponent("dnspire", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }
}

// DNSpireMobileLogCallbackProtocol and DNSpireMobileStatusCallbackProtocol are
// gomobile-generated protocols. We bridge them to Swift closures.

private final class LogSink: NSObject, DNSpireMobileLogCallbackProtocol {
    let handler: (String) -> Void
    init(handler: @escaping (String) -> Void) { self.handler = handler }
    func onLog(_ line: String?) {
        handler(line ?? "")
    }
}

private final class StatusSink: NSObject, DNSpireMobileStatusCallbackProtocol {
    let handler: (String) -> Void
    init(handler: @escaping (String) -> Void) { self.handler = handler }
    func onStatus(_ state: String?) {
        handler(state ?? "")
    }
}
